### ISSUE TITLE
Need to re-think website header links

### ISSUE THREAD

**Issue by errietta** [Pear-Trading/Registration#1]
![screenshot from 2015-02-09 18 13 37](https://cloud.githubusercontent.com/assets/134585/6112368/6741d838-b087-11e4-884b-4d6059ddf214.png)
Links point to the configured BASE_URL followed by the link location. Should this be changed?

**Comment by TBSliver** [comment]
Need to ask @MichaelHallam about what he would like to have on the header, if we are going to have a header at all.

Michael,

Please can you let us know what you would like to be shown on the header of the registration page, and where you would like it to link to.

Thanks.

**Comment by MichaelHallam** [comment]
Is there any way I can see what the registration page currently looks like?
That way I can have some idea about the dimensions for any image (banner? square?)
We have the pear trading logo on file (the one with the words "pear trading" on it). I could also upload a couple of generic trading images that will suit. But you will have to tell me how to do that and where to upload them to.

**Comment by TBSliver** [comment]
Closing as old, will recreate with a better question
