### ISSUE TITLE
Registration emails don't work

### ISSUE THREAD

**Issue by errietta** [Pear-Trading/Registration#16]
Registration requires an email to be sent, but this is currently not working. We should temporarily show the password set/confirmation link to the user instead

12:09 < tcumpsty> Hi, I tried to register for a business account but an e-mail never came through.
12:09 < tcumpsty> (on the test server)
12:10 < tcumpsty> Also, the 'forgot my password' e-mail for ShadowNMS landed in my spam folder (GMail)
12:11 @errietta i don't know if the setup we have for the test server can actually send email at all, i wouldn't be surprised if the answer was no
12:17 < tcumpsty> Okay, I need another way to set up test accounts then, because I'm guessing it is supposed to e-mail me a password (there was no field)
12:21 @errietta xsigh, yes, a reset key is apparently emailed
12:21 @errietta hrmf
12:24 @errietta idn: tcumpsty wants to test the app but he can't make an account because you have to set a password using a key that's emailed to you and the test server is currently
                  either not sending email or the email is getting eaten somewhere... i'm going to make a ticket for this, but do you think it's sane to show the reset link on screen for now
                  while we're testing and have no real users?
12:25 < idn> errietta: Sounds sensible for now.

**Comment by errietta** [comment]
Users now get verification link as of https://github.com/Pear-Trading/Registration/commit/adf211d530be99b539da74fd93af91843006158d (pushed to master)

**Comment by shadowcat-mdk** [comment]
This still errors on the live site at api.peartrading.org/api/

Please could you check asap.

**Comment by shadowcat-mdk** [comment]
There is also a Card ID requested but no one has card IDs as yet so maybe disable this!

**Comment by cumpsty** [comment]
The android app/API uses card IDs in some places to identify traders, and it's used to identify the consumer for transactions.

**Comment by shadowcat-mdk** [comment]
That makes sense, thanks Tom. Might I suggest we have a meeting to discuss the progress and resolve some of these issues as I don't think Michael is aware of the need for a card. We can just replace the card with a different ID right? All we need is an ID token that identifies them for the transactions, the card is likely to be the best but we could just issue them with successive IDs as we use them up so start with Pear000 to Pear999 and then move to Apple? - I would suggest we use test000 for the testing phase if that is the case.

**Comment by MichaelHallam** [comment]
A meeting sounds good.
If you want me there Weds, Thursdays and Fridays are my available days.
As I am only four minutes away from the Shadowcat office I can always pop
round for an update, unless I have a specific meeting elsewhere in my diary.

Michael

**Comment by TBSliver** [comment]
Just going to test if the emails work from the main server, if they do I will re-allow them to work, and fix up some of the code. we will need to go over the email contents however... will put that in a seperate ticket.

**Comment by TBSliver** [comment]
Email works, so will re-enable it on the server. Will also modify the to and from fields slightly for some parts, as they currently go to old admins.

**Comment by MichaelHallam** [comment]
I have nothing sensible to add to this but I just want you folk to know that I am following these updates and am available if anyone wants me. AND I am using the Github to respond :)

**Comment by TBSliver** [comment]
@MichaelHallam yea have noticed :) Once ive got this issue done (which im taking slightly longer over to do it a bit more 'properly') then I will be creating several more tickets - we may need to schedule a meeting or atleast a chat over coffee to go over a few things such as the visual aspects of the app and web portal, as there are a lot of things which are still very much 'BARTER' branding.

**Comment by MichaelHallam** [comment]
I am free from 7th Jan onwards for coffee
Big spaces in diary Wednesdays, Thursdays and Fridays.
Michael
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by TBSliver** [comment]
Will send out a message to everyone tomorrow about a meeting, in the meantime this is fixed!

The new emails are now done using proper templates instead of other insanity, so now they can be edited as normal html files - the two I have created for now are here:

https://github.com/Pear-Trading/Registration/tree/master/templates/email

These are for both a new user and forgotten password stuff.

As this has fixed these issues, i'l resolve this for now.
