### ISSUE TITLE
Regitsration Page second round of changes 2

### ISSUE THREAD

**Issue by MichaelHallam** [Pear-Trading/Registration#3]
RE the Card ID. On the "help" tab it currently drops down and shows the BARTER card. The contents of this dropdown box need to be replaced with "You need to type in the card ID on your card. e.g. PEAR01"

**Comment by errietta** [comment]
Resolved in https://github.com/Pear-Trading/Registration/commit/cbc78069fb7cde9be33fc3fede4d5ca4ad466a96
